### ISSUE TITLE
大神你好，我也在研究deeplabv3+，请问能用pytorch的transfroms代替您说的数据增强吗

### ISSUE THREAD

**Issue by kingqiuol** [gengyanlei/segmentation_pytorch#1]

**Comment by gengyanlei** [comment]
@kingqiuol 你好，很不好意思，我也是菜鸟。嘿嘿，我的回答是可以的。
附上链接： https://github.com/skrypka/imaterialist-furniture-2018/blob/master/misc.py

**Comment by gengyanlei** [comment]
@kingqiuol  以及另一个链接：
https://github.com/hfslyc/AdvSemiSeg/blob/master/dataset/voc_dataset.py

**Comment by kingqiuol** [comment]
@gengyanlei 谢谢大神解答，我刚刚仔细看了您的代码，您是要扩充数据并进行预处理，我的数据够的话直接在读取时进行预处理就行了，好人一生平安

**Comment by gengyanlei** [comment]
@kingqiuol 你好，我的数据量也够。我的代码只是数据增强。另外，预处理可以采用归一化 或 高斯分布。数据增强可以在一定程度上提高网络的性能。
