### ISSUE TITLE
可以跑起来吗？

### ISSUE THREAD

**Issue by lucasjinreal** [gengyanlei/segmentation_pytorch#2]
可以跑起来吗？咋没有结果呢？

**Comment by gengyanlei** [comment]
我没有在ADE数据上跑，网络可以在ISPRS数据上跑。
ADE数据处理，是可以的，但是我用其他的网络跑了一下ADE。仅仅跑了一下。

**Comment by gengyanlei** [comment]
@jinfagang 
我没有在ADE数据上跑，网络可以在ISPRS数据上跑。
ADE数据处理，是可以的，但是我用其他的网络跑了一下ADE。仅仅跑了一下。
