### ISSUE TITLE
你好，想问一下采集的浅层次信息到底是在maxpooling后还是layer1后呢

### ISSUE THREAD

**Issue by zhulanyun** [gengyanlei/segmentation_pytorch#3]

**Comment by gengyanlei** [comment]
@zhulanyun 
你好，才看到，之前一直忙其他的事。论文中是在maxpool之后；但是pyTorch的resnet与tensorflow的不太一样，pytorch的maxpool和layer1输出大小是一样的。我这里就修改成了在layer1后面了。你可以在maxpool后面最好。
