### ISSUE TITLE
为什么你调整的网络没加BN？以及你是怎么理解BN的？

### ISSUE THREAD

**Issue by zuguoqiang** [gengyanlei/segmentation_pytorch#6]
你好，针对deeplab_v3_50.py，我发现你修改的网络普遍不加BN，但是效果也不差。请问你有什么特殊的考虑吗？望指教，谢谢。

**Comment by gengyanlei** [comment]
@zuguoqiang 我写的模型代码 你都跑过？？？
首先，我并不是都不加BN，有的网络没加，有的网络加了。这里deeplab_v3_plus其实是基于resnet50的，这一部分肯定是加BN的，然后ASPP，以及上采样部分是没有添加BN的。BN有用但其实有时候实际训练中也没有太大区别，这个跟应用和网络有一些关系。

**Comment by gengyanlei** [comment]
网上关于BN的作用搜索一下，有很多。
