### ISSUE TITLE
请问如果我换成自己的数据集该怎么做？

### ISSUE THREAD

**Issue by xumeng19** [gengyanlei/segmentation_pytorch#7]
我的数据集size不一样，分辨率很大，是一个二分类问题

**Comment by gengyanlei** [comment]
抱歉，很长时间没有登录github了，才看到。
如果数据大小不一样，有多种解决方法：
1. 滑动窗口裁剪成统一大小
2. 读取图像时，batch=1，这样可以任意大小(不推荐)
3. resize成统一大小
